using namespace vex;
extern brain Brain;
extern controller Controller1;
extern motor leftfront;
extern motor leftrear;
extern motor leftrearstacked;
extern motor rightfront;
extern motor rightrear;
extern motor rightrearstacked;
extern motor_group left_drive;
extern motor_group right_drive;
extern inertial InertialSensor;
void  vexcodeInit( void );